In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [37]:
data={
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,0,0,1]
}

In [38]:
AND=pd.DataFrame(data)

In [39]:
AND

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [40]:
X=AND.drop(columns=['y'])
y=AND['y']
y.to_frame()

   y
0  0
1  0
2  0
3  1

In [41]:
print(X)
print(y)

   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1
0    0
1    0
2    0
3    1
Name: y, dtype: int64

In [42]:
bias=np.c_[X,-np.ones((len(X),1))]

In [43]:
bias

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])

In [ ]:
class Perceptron:
    def __init__(self,eta,epochs):
        self.weights=np.random.rand(3)*1e-4
        print(f"self.weights {self.weights}")
        self.eta=eta
        self.epochs=epochs
        
    def activation_function(self,inputs,weights):
        z=np.dot(inputs,weights)
        return np.where(z<1,0,1)
    def fit(self,x,y):
        self.x=x
        self.y=y
        x_with_bias=np.c_[self.x,-np.ones((len(self.x),1))]
        print(f"x_with_bias: {x_with_bias}")

        y_hat=self.activation_function(x_with_bias,self.weights)
        print(f"y_hat: {y_hat}")

        error=self.y-y_hat
        print(f"error: {error}")


        self.weights=self.weights+self.eta+np.dot(x_with_bias.T,error)

        print(f"updated weights: {self.weights}")

        print("############")

    def predict(self):